import { create } from 'zustand';
import type { VolumeLog, SetCompletionLog } from '../types';
import { useBookStore } from './bookStore';
import { supabase } from '../lib/supabase';

const OWNER_ID = import.meta.env.VITE_OWNER_ID;

export interface SeriesCompletionLog {
  id: string;
  seriesId: string;
  logType: 'series_completion';
  liked: boolean;
  rating: number | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

interface LogState {
  volumeLogs: VolumeLog[];
  setCompletionLogs: SetCompletionLog[];
  seriesCompletionLogs: SeriesCompletionLog[];
  isLoading: boolean;
  loadLogs: () => Promise<void>;
  clearLogs: () => void;
  upsertVolumeLog: (patch: Omit<VolumeLog, 'id' | 'createdAt' | 'updatedAt'>) => Promise<void>;
  updateReadingProgress: (volumeId: string, currentPage: number) => Promise<void>;
  upsertSetCompletionLog: (patch: Pick<SetCompletionLog, 'editionSetId' | 'workId' | 'liked' | 'rating'>) => Promise<void>;
  upsertSeriesCompletionLog: (patch: { seriesId: string; liked: boolean; rating: number | null }) => Promise<void>;
  getVolumeLog: (volumeId: string) => VolumeLog | undefined;
  getSetCompletionLog: (editionSetId: string) => SetCompletionLog | undefined;
  getSeriesCompletionLog: (seriesId: string) => SeriesCompletionLog | undefined;
}

function rowToVolumeLog(row: Record<string, unknown>): VolumeLog {
  const readingState = (row.reading_state as string | undefined) ?? (row.watched ? 'completed' : 'unread');
  return {
    id: row.id as string,
    volumeId: row.volume_id as string,
    editionSetId: row.edition_set_id as string,
    workId: row.work_id as string,
    logType: 'volume',
    watched: readingState === 'completed',
    readingState: readingState as 'unread' | 'reading' | 'completed',
    currentPage: row.current_page as number | null,
    liked: row.liked as boolean,
    rating: row.rating as number | null,
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
  };
}

// [C-5] autoGenerated 누락 수정, updatedAt 제거
function rowToSetLog(row: Record<string, unknown>): SetCompletionLog {
  return {
    id: row.id as string,
    editionSetId: row.edition_set_id as string,
    workId: row.work_id as string,
    logType: 'set_completion',
    autoGenerated: (row.auto_generated as boolean) ?? true,
    liked: row.liked as boolean,
    rating: row.rating as number | null,
    createdAt: row.created_at as string,
  };
}

function rowToSeriesLog(row: Record<string, unknown>): SeriesCompletionLog {
  return {
    id: row.id as string,
    seriesId: row.series_id as string,
    logType: 'series_completion',
    liked: row.liked as boolean,
    rating: row.rating as number | null,
    autoGenerated: row.auto_generated as boolean,
    createdAt: row.created_at as string,
    updatedAt: row.updated_at as string,
  };
}

export const useLogStore = create<LogState>((set, get) => ({
  volumeLogs: [],
  setCompletionLogs: [],
  seriesCompletionLogs: [],
  isLoading: false,

  loadLogs: async () => {
    set({ isLoading: true });
    const { data, error } = await supabase.from('logs').select('*').eq('user_id', OWNER_ID);

    if (error) {
      console.error('Error loading logs:', error);
      set({ isLoading: false });
      return;
    }

    const vLogs = data.filter((r) => r.log_type === 'volume').map(rowToVolumeLog);
    const setLogs = data.filter((r) => r.log_type === 'set_completion').map(rowToSetLog);
    const seriesLogs = data.filter((r) => r.log_type === 'series_completion').map(rowToSeriesLog);

    set({ volumeLogs: vLogs, setCompletionLogs: setLogs, seriesCompletionLogs: seriesLogs, isLoading: false });
  },

  clearLogs: () => {
    set({ volumeLogs: [], setCompletionLogs: [], seriesCompletionLogs: [] });
  },

  upsertVolumeLog: async (patch) => {
    const state = get();
    const existing = state.volumeLogs.find((cl) => cl.volumeId === patch.volumeId);

    const readingState = patch.readingState ?? (patch.watched ? 'completed' : 'unread');
    const watched = readingState === 'completed';

    const payload: Record<string, unknown> = {
      user_id: OWNER_ID,
      volume_id: patch.volumeId,
      edition_set_id: patch.editionSetId,
      work_id: patch.workId,
      log_type: 'volume',
      watched,
      reading_state: readingState,
      current_page: patch.currentPage ?? null,
      liked: patch.liked,
      rating: patch.rating,
      auto_generated: false,
    };

    if (existing) payload.id = existing.id;

    const { data, error } = await supabase.from('logs').upsert(payload, { onConflict: 'id' }).select().single();
    if (error) {
      console.error('Error upserting volume log:', error);
      return;
    }

    let updatedVolumeLogs = state.volumeLogs;
    if (existing) {
      updatedVolumeLogs = updatedVolumeLogs.map(cl =>
        cl.volumeId === patch.volumeId ? rowToVolumeLog(data) : cl
      );
    } else {
      updatedVolumeLogs = [...updatedVolumeLogs, rowToVolumeLog(data)];
    }
    set({ volumeLogs: updatedVolumeLogs });

    // --- set_completion 자동 생성/삭제 (readingState === 'completed' 기준) ---
    const bookState = useBookStore.getState();
    const setVols = bookState.volumes.filter(v => v.editionSetId === patch.editionSetId);
    let setCompletionChanged = false;

    if (setVols.length > 0) {
      const allCompleted = setVols.every(vol => {
        const log = updatedVolumeLogs.find(l => l.volumeId === vol.id);
        return log?.readingState === 'completed';
      });

      const existingCompletion = get().setCompletionLogs.find(l => l.editionSetId === patch.editionSetId);

      if (allCompleted && !existingCompletion) {
        const { data: setData, error: setError } = await supabase.from('logs').upsert({
          user_id: OWNER_ID,
          work_id: patch.workId,
          edition_set_id: patch.editionSetId,
          volume_id: null,
          log_type: 'set_completion',
          watched: false,
          liked: false,
          rating: null,
          auto_generated: true,
        }).select().single();

        if (setError) {
          console.error('Error creating set_completion log:', setError);
        } else if (setData) {
          set(prev => ({ setCompletionLogs: [...prev.setCompletionLogs, rowToSetLog(setData)] }));
          setCompletionChanged = true;
        }
      } else if (!allCompleted && existingCompletion) {
        await supabase.from('logs').delete().eq('id', existingCompletion.id);
        set(prev => ({
          setCompletionLogs: prev.setCompletionLogs.filter(cl => cl.editionSetId !== patch.editionSetId),
        }));
        setCompletionChanged = true;
      }
    }

    // --- series_completion 자동 생성/삭제 ---
    if (setCompletionChanged) {
      const { data: workData } = await supabase
        .from('works').select('series_id').eq('id', patch.workId).single();

      if (workData?.series_id) {
        const seriesId = workData.series_id as string;
        const { data: seriesWorks } = await supabase
          .from('works').select('id').eq('series_id', seriesId);

        if (seriesWorks && seriesWorks.length > 0) {
          const { data: userSetLogs } = await supabase
            .from('logs')
            .select('work_id')
            .eq('user_id', OWNER_ID)
            .eq('log_type', 'set_completion')
            .in('work_id', seriesWorks.map(w => w.id));

          const completedWorkIds = new Set(userSetLogs?.map(l => l.work_id) ?? []);
          const allSeriesWorksCompleted = seriesWorks.every(w => completedWorkIds.has(w.id));
          const existingSeriesLog = get().seriesCompletionLogs.find(l => l.seriesId === seriesId);

          if (allSeriesWorksCompleted && !existingSeriesLog) {
            const { data: newSeriesLog, error: seriesErr } = await supabase
              .from('logs')
              .upsert({
                user_id: OWNER_ID,
                series_id: seriesId,
                log_type: 'series_completion',
                watched: false,
                liked: false,
                rating: null,
                auto_generated: true,
              })
              .select()
              .single();

            if (seriesErr) {
              console.error('Error creating series_completion log:', seriesErr);
            } else if (newSeriesLog) {
              set(prev => ({
                seriesCompletionLogs: [...prev.seriesCompletionLogs, rowToSeriesLog(newSeriesLog)],
              }));
            }
          } else if (!allSeriesWorksCompleted && existingSeriesLog) {
            await supabase.from('logs').delete().eq('id', existingSeriesLog.id);
            set(prev => ({
              seriesCompletionLogs: prev.seriesCompletionLogs.filter(l => l.seriesId !== seriesId),
            }));
          }
        }
      }
    }
  },

  updateReadingProgress: async (volumeId, currentPage) => {
    const state = get();
    const existing = state.volumeLogs.find(l => l.volumeId === volumeId);
    if (!existing) return;

    const { data, error } = await supabase
      .from('logs')
      .update({ current_page: currentPage })
      .eq('id', existing.id)
      .select()
      .single();

    if (error) {
      console.error('Error updating reading progress:', error);
      return;
    }

    set(prev => ({
      volumeLogs: prev.volumeLogs.map(l => l.volumeId === volumeId ? rowToVolumeLog(data) : l),
    }));
  },

  upsertSetCompletionLog: async (patch) => {
    const state = get();
    const existing = state.setCompletionLogs.find(cl => cl.editionSetId === patch.editionSetId);
    if (!existing) return;

    const updated: SetCompletionLog = { ...existing, liked: patch.liked, rating: patch.rating };
    set({
      setCompletionLogs: state.setCompletionLogs.map(cl =>
        cl.editionSetId === patch.editionSetId ? updated : cl
      ),
    });

    const { error } = await supabase.from('logs').upsert({
      id: existing.id,
      user_id: OWNER_ID,
      work_id: patch.workId,
      edition_set_id: patch.editionSetId,
      volume_id: null,
      log_type: 'set_completion',
      watched: false,
      liked: patch.liked,
      rating: patch.rating,
      auto_generated: true,
    }, { onConflict: 'id' });

    if (error) console.error('Error upserting set_completion log:', error);
  },

  upsertSeriesCompletionLog: async (patch) => {
    const state = get();
    const existing = state.seriesCompletionLogs.find(cl => cl.seriesId === patch.seriesId);

    const payload: Record<string, unknown> = {
      user_id: OWNER_ID,
      series_id: patch.seriesId,
      log_type: 'series_completion',
      watched: false,
      liked: patch.liked,
      rating: patch.rating,
      auto_generated: existing ? existing.autoGenerated : false,
    };

    if (existing) payload.id = existing.id;

    const { data, error } = await supabase
      .from('logs')
      .upsert(payload, { onConflict: 'id' })
      .select()
      .single();

    if (error || !data) {
      console.error('Error upserting series log:', error);
      return;
    }

    const updatedLog = rowToSeriesLog(data);
    set(prev => ({
      seriesCompletionLogs: existing
        ? prev.seriesCompletionLogs.map(cl => cl.seriesId === patch.seriesId ? updatedLog : cl)
        : [...prev.seriesCompletionLogs, updatedLog],
    }));
  },

  getVolumeLog: (volumeId) => get().volumeLogs.find(l => l.volumeId === volumeId),
  getSetCompletionLog: (editionSetId) => get().setCompletionLogs.find(l => l.editionSetId === editionSetId),
  getSeriesCompletionLog: (seriesId) => get().seriesCompletionLogs.find(l => l.seriesId === seriesId),
}));
