export interface Translation {
  key: string;
  label: string;
  text: string;
}

export interface Work {
  id: string;
  title: string;
  author: string;
  publishedYear: number;
  description: string;
  coverImageUrl: string;
  genre: string;
  lists?: string[];          // [H-5] lists 필드 추가
  translations?: Translation[];
}

export interface EditionSet {
  id: string;
  workId: string;
  publisher: string;
  coverImageUrl: string;
  publishedYear: number;
}

export interface Volume {
  id: string;
  editionSetId: string;
  volumeNumber: number;
  title: string;
}

export interface VolumeLog {
  id: string;
  volumeId: string;
  editionSetId: string;
  workId: string;
  logType: 'volume';
  watched: boolean;
  readingState: 'unread' | 'reading' | 'completed';
  currentPage: number | null;
  liked: boolean;
  rating: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface SetCompletionLog {
  id: string;
  editionSetId: string;
  workId: string;
  logType: 'set_completion';
  autoGenerated: boolean;    // [C-5] true 리터럴 → boolean으로 완화 (실제 DB값 반영)
  liked: boolean;
  rating: number | null;
  createdAt: string;
  // updatedAt 제거 — DB 스키마에 없음
}

export type AnyLog = VolumeLog | SetCompletionLog;

export interface SearchCandidate {
  workId: string;
  title: string;
  author: string;
  coverImageUrl: string;
  genre: string;
}

// --- Flowchart Types ---

import type { Node, Edge } from '@xyflow/react';

export interface FlowchartNodeData {
  workId: string;
  label: string;
  [key: string]: unknown; // required by @xyflow/react NodeData constraint
}

export type FlowchartNodeType = 'entry' | 'main' | 'side';
export type FlowchartNode = Node<FlowchartNodeData, FlowchartNodeType>;
export type FlowchartEdge = Edge;

export interface DbFlowchart {
  id: string;
  author_name: string;
  nodes: FlowchartNode[];
  edges: FlowchartEdge[];
  created_at: string;
  updated_at: string;
}
